name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: dockerhub login
      run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build image 
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-app:latest ./api

    - name: Push latest tag
      run: docker push ${{ secrets.DOCKER_USERNAME }}/my-app:latest ./api

    - name: Tag with commit SHA and push
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/my-app:latest ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }}

